language: python
python:
  - 3.6

notifications:
  email: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdal-dev
  - gdal-config --version
  - pip install --upgrade pip

# command to install pygdal
install:
   - pip install -v -e ./$(gdal-config --version)

install:
  - pip install -r requirements.txt

script:
  - nosetests -v

